[package]
name = "pictorus_traits"
version = "0.2.0"
edition = "2021"
publish = [ "pictorus",]
description = "Traits for creating custom Pictorus blocks"
license = "GPL-3.0"
homepage = "https://pictor.us"

[dependencies]

[dev-dependencies]
heapless = "0.8.0"
log = "0.4.21"
