[package]
name = "linux-protocols"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../../utils" }
protocols = { path = "../../protocols", features = [ "can",] }
chrono = "0.4.34"
embedded-hal = "1.0.0"
embedded-hal-02 = { package = "embedded-hal", version = "0.2.6", features = [ "unproven",] }
embedded-io = { version = "0.6.1", features = [ "std",] }
libc = "0.2.153"
linux-embedded-hal = "0.4.0"
log = "0.4.21"
std-embedded-time = "0.1.0"
sysfs-pwm = "0.1.0"
serialport = "4.3.0"
embedded-can = "0.4.1"
socketcan = "3.3.0"
nb = "1.1.0"

[features]
default = [ "spi",]
spi = [ "protocols/spi",]
